const iconMapping: Record<string, string> = {
	TEMP: "fa-solid fa-cubes-stacked",
	ASET: "fa-regular fa-rectangle-list",
	CPPT: "fa-solid fa-diagram-project",
	TEXT: "fa-regular fa-image",
	TEXD: "fa-regular fa-image",
	MRTN: "fa-solid fa-person-running",
	FXAS: "fa-solid fa-person-running",
	ATMD: "fa-solid fa-person-running",
	UICT: "fa-regular fa-window-restore",
	PRIM: "fa-solid fa-shapes",
	WSGT: "fa-solid fa-volume-high",
	WSWT: "fa-solid fa-volume-high",
	WBNK: "fa-solid fa-volume-high",
	WWEV: "fa-solid fa-volume-high",
	WWFX: "fa-solid fa-explosion",
	WWEM: "fa-solid fa-music",
	WWES: "fa-solid fa-comments",
	SDEF: "fa-solid fa-comments",
	DLGE: "fa-solid fa-closed-captioning",
	LOCR: "fa-solid fa-language",
	RTLV: "fa-regular fa-closed-captioning",
	REPO: "fa-solid fa-code",
	JSON: "fa-solid fa-code",
	ORES: "fa-solid fa-code",
	GFXV: "fa-solid fa-film",
	LINE: "fa-solid fa-comment",
	CRMD: "fa-solid fa-people-group",
	NAVP: "fa-solid fa-route",
	AIRG: "fa-solid fa-route",
	AIBX: "fa-regular fa-user",
	AIBZ: "fa-regular fa-user",
	YSHP: "fa-solid fa-baseball-bat-ball",
	ALOC: "fa-solid fa-car-burst",
	TBLU: "fa-regular fa-square",
	CBLU: "fa-regular fa-square",
	ASEB: "fa-regular fa-square",
	UICB: "fa-regular fa-square",
	MATB: "fa-regular fa-square",
	WSWB: "fa-regular fa-square",
	DSWB: "fa-regular fa-square",
	ECPB: "fa-regular fa-square",
	WSGB: "fa-regular fa-square"
}

export function getIconForResourceType(filetype: string): string {
	return iconMapping[filetype] || "fa-regular fa-file"
}
